config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  }

  namespace :admin do
    get '/' => 'homes#top', as:'home'

    get '/items' => 'items#index', as:'item'
    get '/items/new' => 'items#new', as:'item_new'
    post '/item' => 'items#create', as:'item_create'
    get '/items/:id' => 'items#show', as:'item_show'
    get '/items/:id/edit' => 'items#edit', as:'item_edit'
    patch 'items/:id' => 'items#update', as:'item_update'
    get "/search" => "items#search"

    get '/customers' => 'customers#index', as:'customers'
    get '/customers/:id' => 'customers#show', as:'customers_show'
    get '/customers/:id/edit' => 'customers#edit', as:'customers_edit'
    patch '/customers/:id' => 'customers#update', as:'customers_update'

    get '/orders/:id' => 'orders#show', as:'orders_show'
    patch '/orders/:id' => 'orders#update', as:'orders_update'

    patch '/:order_id/order_details/:id' => 'order_details#update', as:'order_detail_update'

    get '/genres' => 'genres#index', as:'genres'
    post '/genre' => 'genres#create', as:'genres_create'
    get '/genres/:id/edit' => 'genres#edit', as:'genres_edit'
    patch '/genres/:id' => 'genres#update', as:'genres_update'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as:'about'

    get '/items' => 'items#index', as:'item'
    get '/items/:id' => 'items#show', as:'item_show'
    get "/search" => "items#search"

    get '/customers' => 'customers#show', as:'customer_show'
    get '/customers/information/edit' => 'customers#edit', as:'customer_edit'
    patch '/customers/information' => 'customers#update', as:'customer_update'
    get '/customers/confirm_withdraw' => 'customers#confirm_withdraw', as:'customer_confirm_withdraw'
    patch '/customers/withdraw' => 'customers#withdraw', as:'customer_withdraw'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as:'cart_items_destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    get '/orders/new' => 'orders#new', as:'order_new'
    get '/orders/thanks' => 'orders#thanks', as:'order_thanks'
    get '/orders' => 'orders#index', as:'order'
    get '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/:id' => 'orders#show', as:'order_show'
    post '/orders' => 'orders#create', as:'orders'

    get '/deliveries' => 'deliveries#index', as:'deliveries'
    post '/deliveries' => 'deliveries#create', as:'deliveries_create'
    get '/deliveries/:id/edit' => 'deliveries#edit', as:'deliveries_edit'
    patch '/deliveries/:id' => 'deliveries#update', as:'deliveries_update'
    delete '/deliveries/:id' => 'deliveries#destroy', as:'deliveries_destroy'
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_detail
  has_many :cart_item

  def tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_show_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_show_path(@item.id)
  end

  def search
    @items = Item.all
    @items = @items.where('name LIKE ?', "%#{params[:search]}%") if params[:seach].present?
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :sale_status, :image, :genre_id)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-1">
      <h5 class="p-3"><span style="background-color:#dcdcdc;">　商品編集　</span></h5>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-9 offset-lg-3">
      <table class="table table-borderless">
        <tbody>
          <%= form_with model: @item, url: admin_item_update_path, method: :patch do |f| %>
            <tr>
              <td class="col-lg-2">商品画像</td>
              <td ><%= f.file_field :image %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">商品名</td>
              <td style="padding-top: 0px"><%= f.text_field :name, :size=>"35" %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">商品説明</td>
              <td style="padding-top: 0px"><%= f.text_area :introduction, :size=>"37.5" %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">ジャンル</td>
              <td style="padding-top: 0px; width: 295px;"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_display, @item.genre_id), {prompt: "-- 選択してください --"}, {style: 'width: 295px;'} %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">税抜価格</td>
              <td style="padding-top: 0px"><%= f.text_field :price, :size=>"35" %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">販売ステータス</td>
              <td style="padding-top: 0px">
                <span style="margin-right: 10px;"><%= f.radio_button :sale_status, true %><%= f.label :sale_status_true, "販売中" %></span>
                <%= f.radio_button :sale_status, false %><%= f.label :sale_status_false, "販売中止" %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>
                <span style="margin-left: 80px;"><%= f.submit "変更を保存", class: "btn btn-success" %></td>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-1">
      <h5 class="p-3"><span style="background-color:#dcdcdc;">　商品一覧　</span></h5>
    </div>
    <div class="social col-lg-1 d-flex justify-content-end p-3">
      <%= link_to admin_item_new_path do %>
        <i class="fa-solid fa-circle-plus fa-lg" style="color: #aaaeb5;"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10 offset-lg-1 px-0 border-top border-bottom">
      <table class="table table-borderless">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th class="col-lg-4">商品名</th>
            <th>税抜価格</th>
            <th class="col-lg-3">ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td>
                <%= link_to admin_item_show_path(item.id) do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td><%= item.price %> </td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.sale_status == true %>
                  <span class="font-weight-bold" style="color:#00AA00;">販売中</span>
                <% else %>
                  <span class="font-weight-bold"  style="color:#C0C0C0;">販売停止中</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row d-flex justify-content-center p-2">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-1">
      <h5 class="p-3"><span style="background-color:#dcdcdc;">　商品新規登録　</span></h5>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-9 offset-lg-3">
      <table class="table table-borderless">
        <tbody>
          <%= form_with model: @item, url: admin_item_create_path, method: :post do |f| %>
            <tr>
              <td class="col-lg-2">商品画像</td>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">商品名</td>
              <td style="padding-top: 0px"><%= f.text_field :name, placeholder:"商品名", :size=>"35" %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">商品説明</td>
              <td style="padding-top: 0px"><%= f.text_area :introduction, placeholder:"ここに説明文を記述します", :size=>"37.5" %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">ジャンル</td>
              <td style="padding-top: 0px;"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_display), {prompt: "-- 選択してください --"}, {style: 'width: 295px;'} %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">税抜価格</td>
              <td style="padding-top: 0px"><%= f.text_field :price, placeholder:"1000", :size=>"35" %>円</td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">販売ステータス</td>
              <td style="padding-top: 0px">
                <span style="margin-right: 10px;"><%= f.radio_button :sale_status, true %><%= f.label :sale_status_true, "販売中" %></span>
                <%= f.radio_button :sale_status, false %><%= f.label :sale_status_false, "販売中止" %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>
                <span style="margin-left: 80px;"><%= f.submit "　新規登録　", class: "btn btn-success" %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <h5 class="p-3"><span style="background-color:#dcdcdc;">　商品詳細　</span></h5>
    </div>
　</div>
　<div class="row">
    <div class="col-lg-3 offset-lg-1">
      <% if @item.image.attached? %>
        <%= image_tag @item.image, size:"200x150" %>
      <% else %>
        <%= image_tag 'no_image', size:"200x150" %>
      <% end %>
    </div>
    <div class="col-lg-8">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td class="col-lg-3" style="padding-top: 0px">商品説明</td>
            <td style="padding-top: 0px"><%= @item.introduction %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">ジャンル</td>
            <td style="padding-top: 0px"><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">税込価格</br>(税抜価格)</td>
            <td><%= @item.tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)円</td>
          </tr>
          <tr>
            <td style="padding-top: 0px">販売ステータス</td>
            <td style="padding-top: 0px">
              <% if @item.sale_status == true %>
                <span class="font-weight-bold" style="color:#00AA00;">販売中</span>
              <% else %>
                <span class="font-weight-bold"  style="color:#C0C0C0;">販売停止中</span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row d-flex justify-content-center" style="margin-bottom: 100px;">
    <%= link_to "　編集する　", admin_item_edit_path(@item.id), class: 'btn btn-success' %>
  </div>
</div>