config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  }

  namespace :admin do
    get '/' => 'homes#top', as:'home'

    get '/items' => 'items#index', as:'item'
    get '/items/new' => 'items#new', as:'item_new'
    post '/item' => 'items#create', as:'item_create'
    get '/items/:id' => 'items#show', as:'item_show'
    get '/items/:id/edit' => 'items#edit', as:'item_edit'
    patch 'items/:id' => 'items#update', as:'item_update'
    get "/search" => "items#search"

    get '/customers' => 'customers#index', as:'customers'
    get '/customers/:id' => 'customers#show', as:'customers_show'
    get '/customers/:id/edit' => 'customers#edit', as:'customers_edit'
    patch '/customers/:id' => 'customers#update', as:'customers_update'

    get '/orders/:id' => 'orders#show', as:'orders_show'
    patch '/orders/:id' => 'orders#update', as:'orders_update'

    patch '/:order_id/order_details/:id' => 'order_details#update', as:'order_detail_update'

    get '/genres' => 'genres#index', as:'genres'
    post '/genre' => 'genres#create', as:'genres_create'
    get '/genres/:id/edit' => 'genres#edit', as:'genres_edit'
    patch '/genres/:id' => 'genres#update', as:'genres_update'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as:'about'

    get '/items' => 'items#index', as:'item'
    get '/items/:id' => 'items#show', as:'item_show'
    get "/search" => "items#search"

    get '/customers' => 'customers#show', as:'customer_show'
    get '/customers/information/edit' => 'customers#edit', as:'customer_edit'
    patch '/customers/information' => 'customers#update', as:'customer_update'
    get '/customers/confirm_withdraw' => 'customers#confirm_withdraw', as:'customer_confirm_withdraw'
    patch '/customers/withdraw' => 'customers#withdraw', as:'customer_withdraw'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as:'cart_items_destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    get '/orders/new' => 'orders#new', as:'order_new'
    get '/orders/thanks' => 'orders#thanks', as:'order_thanks'
    get '/orders' => 'orders#index', as:'order'
    get '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/:id' => 'orders#show', as:'order_show'
    post '/orders' => 'orders#create', as:'orders'

    get '/deliveries' => 'deliveries#index', as:'deliveries'
    post '/deliveries' => 'deliveries#create', as:'deliveries_create'
    get '/deliveries/:id/edit' => 'deliveries#edit', as:'deliveries_edit'
    patch '/deliveries/:id' => 'deliveries#update', as:'deliveries_update'
    delete '/deliveries/:id' => 'deliveries#destroy', as:'deliveries_destroy'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries
  has_many :cart_items
  has_many :orders

  def full_name
    self.last_name + self.first_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_show_path(@customer.id)
  end

 private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-1">
      <h5 class="p-3"><span style="background-color:#dcdcdc;">　<%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集　</span></h5>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <table class="table table-borderless">
        <tbody>
          <%= form_with model: @customer, url: admin_customers_update_path, method: :patch do |f| %>
            <tr>
              <td td class="col-lg-2">会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">氏名</td>
              <td style="padding-top: 0px">
                <span style="margin-right: 30px;"><%= f.text_field :last_name %></span>
                <%= f.text_field :first_name %>
              </td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">フリガナ</td>
              <td style="padding-top: 0px">
                <span style="margin-right: 30px;"><%= f.text_field :last_name_kana %></span>
                <%= f.text_field :first_name_kana %>
              </td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">郵便番号</td>
              <td style="padding-top: 0px"><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">住所</td>
              <td style="padding-top: 0px"><%= f.text_field :address, :size=>"80" %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">電話番号</td>
              <td style="padding-top: 0px"><%= f.text_field :telephone_number %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">メールアドレス</td>
              <td style="padding-top: 0px"><%= f.email_field :email %></td>
            </tr>
            <tr>
              <td class="col-lg-2" style="padding-top: 0px">会員ステータス</td>
              <td style="padding-top: 0px;">
                <span style="margin-right: 10px;"><%= f.radio_button :is_deleted, false %><%= f.label :sale_status_false, "有効" %></span>
                <%= f.radio_button :is_deleted, true %><%= f.label :sale_status_true, "退会" %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-1">
      <h5 class="p-3"><span style="background-color:#dcdcdc;">　会員一覧　</span></h5>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-lg-9 offset-lg-1 px-0">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th class="col-lg-1">会員ID</th>
            <th class="col-lg-3">氏名</th>
            <th class="col-lg-3">メールアドレス</th>
            <th class="col-lg-2">ステータス</th>
          </tr>
        </thead>
        <tbody class="border-bottom">
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customers_show_path(customer.id) do %>
                  <%= customer.last_name %><%= customer.first_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted == false %>
                  <span class="font-weight-bold" style="color:#00AA00;">有効</span>
                <% else %>
                  <span class="font-weight-bold"  style="color:#C0C0C0;">退会</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row d-flex justify-content-center p-2">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <h5 class="p-3"><span style="background-color:#dcdcdc;">　<%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細　</span></h5>
    </div>
　</div>
  <div class="row">
    <div class="col-lg-5 offset-lg-1">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">氏名</td>
            <td style="padding-top: 0px"><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">フリガナ</td>
            <td style="padding-top: 0px"><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">郵便番号</td>
            <td style="padding-top: 0px"><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">住所</td>
            <td style="padding-top: 0px"><%= @customer.address %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">電話番号</td>
            <td style="padding-top: 0px"><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">メールアドレス</td>
            <td style="padding-top: 0px"><%= @customer.email %></td>
          </tr>
          <tr>
            <td style="padding-top: 0px">会員ステータス</td>
            <td style="padding-top: 0px">
              <% if @customer.is_deleted == false %>
                <span class="font-weight-bold" style="color:#00AA00;">有効</span>
              <% else %>
                <span class="font-weight-bold"  style="color:#C0C0C0;">退会</span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row" style="margin-bottom: 100px;">
    <div class="col-lg-2 offset-lg-3" style="padding-left: 40px;">
      <%= link_to "　編集する　", admin_customers_edit_path(@customer.id), class: 'btn btn-success' %>
    </div>
    <div class="col-lg-3">
      <%= link_to "　注文履歴一覧を見る　", admin_home_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>