config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  }

  namespace :admin do
    get '/' => 'homes#top', as:'home'

    get '/items' => 'items#index', as:'item'
    get '/items/new' => 'items#new', as:'item_new'
    post '/item' => 'items#create', as:'item_create'
    get '/items/:id' => 'items#show', as:'item_show'
    get '/items/:id/edit' => 'items#edit', as:'item_edit'
    patch 'items/:id' => 'items#update', as:'item_update'
    get "/search" => "items#search"

    get '/customers' => 'customers#index', as:'customers'
    get '/customers/:id' => 'customers#show', as:'customers_show'
    get '/customers/:id/edit' => 'customers#edit', as:'customers_edit'
    patch '/customers/:id' => 'customers#update', as:'customers_update'

    get '/orders/:id' => 'orders#show', as:'orders_show'
    patch '/orders/:id' => 'orders#update', as:'orders_update'

    patch '/:order_id/order_details/:id' => 'order_details#update', as:'order_detail_update'

    get '/genres' => 'genres#index', as:'genres'
    post '/genre' => 'genres#create', as:'genres_create'
    get '/genres/:id/edit' => 'genres#edit', as:'genres_edit'
    patch '/genres/:id' => 'genres#update', as:'genres_update'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as:'about'

    get '/items' => 'items#index', as:'item'
    get '/items/:id' => 'items#show', as:'item_show'
    get "/search" => "items#search"

    get '/customers' => 'customers#show', as:'customer_show'
    get '/customers/information/edit' => 'customers#edit', as:'customer_edit'
    patch '/customers/information' => 'customers#update', as:'customer_update'
    get '/customers/confirm_withdraw' => 'customers#confirm_withdraw', as:'customer_confirm_withdraw'
    patch '/customers/withdraw' => 'customers#withdraw', as:'customer_withdraw'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as:'cart_items_destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    get '/orders/new' => 'orders#new', as:'order_new'
    get '/orders/thanks' => 'orders#thanks', as:'order_thanks'
    get '/orders' => 'orders#index', as:'order'
    get '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/:id' => 'orders#show', as:'order_show'
    post '/orders' => 'orders#create', as:'orders'

    get '/deliveries' => 'deliveries#index', as:'deliveries'
    post '/deliveries' => 'deliveries#create', as:'deliveries_create'
    get '/deliveries/:id/edit' => 'deliveries#edit', as:'deliveries_edit'
    patch '/deliveries/:id' => 'deliveries#update', as:'deliveries_update'
    delete '/deliveries/:id' => 'deliveries#destroy', as:'deliveries_destroy'
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  def subtotal
    item.tax_price * amount
  end

  def get_amount(order)
    total = 0
    order.order_details.each do |order_detail|
      total += order_detail.amount
    end
    return total
  end

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, making: 2, preparing_to_ship: 3, shipped: 4 }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @customer = @order.customer
    @sum = 0
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(crafting_status: 1) if @order.order_status == "payment_confirmation"
    end
    redirect_to admin_orders_show_path(@order.id)

  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:crafting_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-1">
      <h5 class="p-3"><span style="background-color:#dcdcdc;">　注文履歴詳細　</span></h5>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-7" style="padding-left: 40px;">
      <table class="table table-borderless table-sm">
        <tbody>
          <%= form_with model: @order, url: admin_orders_update_path, method: :patch do |f| %>
          <tr>
            <td class="col-lg-3 font-weight-bold" style="font-size:17px;">購入者</td>
            <td style="font-size:17px;">
              <%= link_to admin_customers_show_path(@customer.id) do %>
                <%= @order.customer.last_name %><%= @order.customer.first_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td class="col-lg-3 font-weight-bold" style="font-size:17px;">注文日</td>
            <td style="font-size:17px;"><%= localize @order.created_at, format: :short %></td>
          </tr>
          <tr>
            <td class="col-lg-3 font-weight-bold" style="font-size:17px;">配送先</td>
            <td style="font-size:17px;">
              〒<%= @order.postal_code %><span style="margin-left: 10px;"><%= @order.address %></span></br>
              <%= @order.name %>
            </td>
          </tr>
          <tr>
            <td class="col-lg-3 font-weight-bold" style="font-size:17px;">支払い方法</td>
            <td style="font-size:17px;"><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <td class="col-lg-3 font-weight-bold" style="font-size:17px;">注文ステータス</td>
            <td style="font-size:17px;"><%= f.select :order_status, Order.order_statuses_i18n.keys.map{|status| [I18n.t("enums.order.order_status.#{status}"),status]} %>
              <span style="margin-left: 20px;"><%= f.submit "更新", class: "btn btn-success" %></span>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<!-- order_details -->
  <div class="row">
    <div class="col-lg-8" style="padding-left: 40px; margin-top: 10px;">
      <table class="table table-borderless border-top border-bottom">
        <thead class="thead-light">
          <tr>
            <th class="col-lg-2">商品名</th>
            <th class="col-lg-1">単価(税込)</th>
            <th class="col-lg-1" style="padding-left: 30px;">数量</th>
            <th class="col-lg-1" style="padding-left: 30px;">小計</th>
            <th class="col-lg-2" style="padding-left: 10px;">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td class="align-middle">
              <%= order_detail.item.name %>
            </td>
            <td class="align-middle" style="text-align:center;">
              <%= order_detail.item.tax_price.to_s(:delimited) %>
            </td>
            <td class="align-middle" style="text-align:center;">
              <%= order_detail.amount %>
            </td>
            <td class="align-middle" style="text-align:center;">
              <%= order_detail.subtotal %>
            </td>
            <td class="align-middle" style="text-align:center;">
              <%= form_with model: order_detail, url: admin_order_detail_update_path(order_id: @order, id: order_detail), method: :patch do |f| %>
                <%= f.select :crafting_status, OrderDetail.crafting_statuses_i18n.invert %>
                <span style="margin-left: 25px;"><%= f.submit "更新", class: "btn btn-success" %></span>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-4 d-flex align-items-end" style="padding-left: 80px; margin-top: 10px;">
      <table class="table table-borderless table-sm">
        <tbody>
          <tr>
            <td width="130px" class="font-weight-bold" style="font-size:17px;">合計金額</td>
            <td>
              <% @sum =  @order.invoice_amount - @order.postage %>
              <%= @sum.to_s(:delimited) %>円
            </td>
          </tr>
          <tr>
            <td class="font-weight-bold" style="font-size:17px;">送料</td>
            <td><%= @order.postage %>円</td>
          </tr>
          <tr>
            <td class="font-weight-bold" style="font-size:17px;">請求金額合計</td>
            <td class="font-weight-bold"><%= @order.invoice_amount.to_s(:delimited) %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>