config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  }

  namespace :admin do
    get '/' => 'homes#top', as:'home'

    get '/items' => 'items#index', as:'item'
    get '/items/new' => 'items#new', as:'item_new'
    post '/item' => 'items#create', as:'item_create'
    get '/items/:id' => 'items#show', as:'item_show'
    get '/items/:id/edit' => 'items#edit', as:'item_edit'
    patch 'items/:id' => 'items#update', as:'item_update'
    get "/search" => "items#search"

    get '/customers' => 'customers#index', as:'customers'
    get '/customers/:id' => 'customers#show', as:'customers_show'
    get '/customers/:id/edit' => 'customers#edit', as:'customers_edit'
    patch '/customers/:id' => 'customers#update', as:'customers_update'

    get '/orders/:id' => 'orders#show', as:'orders_show'
    patch '/orders/:id' => 'orders#update', as:'orders_update'

    patch '/:order_id/order_details/:id' => 'order_details#update', as:'order_detail_update'

    get '/genres' => 'genres#index', as:'genres'
    post '/genre' => 'genres#create', as:'genres_create'
    get '/genres/:id/edit' => 'genres#edit', as:'genres_edit'
    patch '/genres/:id' => 'genres#update', as:'genres_update'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as:'about'

    get '/items' => 'items#index', as:'item'
    get '/items/:id' => 'items#show', as:'item_show'
    get "/search" => "items#search"

    get '/customers' => 'customers#show', as:'customer_show'
    get '/customers/information/edit' => 'customers#edit', as:'customer_edit'
    patch '/customers/information' => 'customers#update', as:'customer_update'
    get '/customers/confirm_withdraw' => 'customers#confirm_withdraw', as:'customer_confirm_withdraw'
    patch '/customers/withdraw' => 'customers#withdraw', as:'customer_withdraw'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as:'cart_items_destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    get '/orders/new' => 'orders#new', as:'order_new'
    get '/orders/thanks' => 'orders#thanks', as:'order_thanks'
    get '/orders' => 'orders#index', as:'order'
    get '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/:id' => 'orders#show', as:'order_show'
    post '/orders' => 'orders#create', as:'orders'

    get '/deliveries' => 'deliveries#index', as:'deliveries'
    post '/deliveries' => 'deliveries#create', as:'deliveries_create'
    get '/deliveries/:id/edit' => 'deliveries#edit', as:'deliveries_edit'
    patch '/deliveries/:id' => 'deliveries#update', as:'deliveries_update'
    delete '/deliveries/:id' => 'deliveries#destroy', as:'deliveries_destroy'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries
  has_many :cart_items
  has_many :orders

  def full_name
    self.last_name + self.first_name
  end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer

  def deliveries_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  def genre_display
    name
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_detail
  has_many :cart_item

  def tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  def subtotal
    item.tax_price * amount
  end

  def get_amount(order)
    total = 0
    order.order_details.each do |order_detail|
      total += order_detail.amount
    end
    return total
  end

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, making: 2, preparing_to_ship: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum crafting_status: { not_make: 0, waiting_to_make: 1, making: 2, completed: 3 }

  def subtotal
    item.tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_show_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_show_path(@item.id)
  end

  def search
    @items = Item.all
    @items = @items.where('name LIKE ?', "%#{params[:search]}%") if params[:seach].present?
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :sale_status, :image, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  private

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_after_sign_in_admin.html.erb
<li class="d-flex justify-content-end">
  <%= link_to "商品一覧", admin_item_path, class: "btn btn-outline-secondary m-3" %>
  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary m-3" %>
  <%= link_to "注文履歴一覧", admin_home_path, class: "btn btn-outline-secondary m-3" %>
  <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary m-3" %>
  <%= link_to "ログアウト", destroy_admin_session_path, class: "btn btn-outline-secondary m-3", method: :delete %>
</li>

<!--
<li class="input-group d-flex justify-content-end m-3">
  <%#= form_with url: admin_search_path, method: :get, loccal: true do |f| %>
    <%#= f.text_field :word %>
    <%#= f.submit "Search" %>
  <%# end %>
</li>
-->

app/views/admin/shared/_before_sign_in.html.erb
<li class="d-flex justify-content-end">
  <%= link_to "About", about_path, class: "btn btn-outline-secondary m-3" %>
  <%= link_to "商品一覧", item_path, class: "btn btn-outline-secondary m-3" %>
  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary m-3" %>
  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary m-3" %>
</li>

<!--
<li class="input-group d-flex justify-content-end m-3">
  <%#= form_with url: admin_search_path, method: :get, loccal: true do |f| %>
    <%#= f.text_field :word %>
    <%#= f.submit "Search" %>
  <%# end %>
</li>
-->

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCake</title>
    <script src="https://kit.fontawesome.com/a6ef0cdc17.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <div class="container p-4">
        <div class="row">
          <div class="col-lg-4">
            <nav class="navbar navbar-left ml-2">
              <%= link_to image_tag("ロゴ.jpg", size: '150x120'), root_path %>
            </nav>
          </div>
          <div class="col-lg-8">
          <nav>
            <ul class="nav navbar-nav navbar-right ml-auto">
              <% if customer_signed_in? %>
                <li class="nav-item"><%= render 'public/shared/after_sign_in_public' %></li>
              <% elsif admin_signed_in? %>
                <li class="nav-item"><%= render 'admin/shared/after_sign_in_admin' %></li>
              <% else %>
                <li class="nav-item"><%= render 'admin/shared/before_sign_in' %></li>
              <% end %>
            </ul>
          </nav>
          </div>
        </div>
      </div>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
       <div class="container mb-3 mt-3 ">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight © 2023 NAGANOCake Inc.</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>